# Site settings
name: 从菜鸟至今
email: 375160958@qq.com
author: Panda Pan
url: https://pandapanzhu.github.io/
# resume_site: http://www.hifreud.com/Resume.io/ #个人简历
github: https://github.com/pandapanzhu/
baseurl: ""
description: wlcome to here! 
meta_description: This is panda pan`s blog
motto: I hope I have something for you.
banner: Life is a process of constant exploration, isn't it?

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: pandapanzhu
highlighter: rouge

# Build settings
markdown: kramdown

#FB:
#  comments :
#   provider : duoshuo
#    duoshuo:
#        short_name : luoyan35714
#    disqus :
#        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light